### PR TITLE
Fixed axios default url

### LINKED ISSUE #25: Change Axios defaulturl instead of string concat.
https://axios-http.com/docs/config_defaults

Practically just set the defaulturl to the backend url.

### PR DESCRIPTION
**Pull request by Konolo**
Closes #25

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ let rl = readline.createInterface({
 
 const waitForInput = () => {
   rl.question('Input ID:\n', async (idNum) => {    
-    const result = await axios.post(backendURL! + 'v1/checkin', {
+    const result = await axios.post('/checkin', {
```
Comment (SpBills) [inline src/main.ts:39]: Note that we will have to put /v1 at the end of the env.

**Review by SpBills — APPROVED** [review]
LGTM
