### PR TITLE
WS does not crash program

### LINKED ISSUE #23: Handle Frontend inability to connect Crash
Currently the frontend crashes if it cannot connect to the backend. This should output some special data, or gracefully exit.

### PR DESCRIPTION
**Pull request by SebastianNeiswanger**
Errors send a log, and if it connects and disconnects the program is still good. 

Test starting the terminal, then the backend, wait for the heartbeat to go through, then close the backend to make sure the program still is able to survive.

Potentially if you close the backend at the exact millisecond that the if statement verifies the WS is still open, then you could still crash the program when it tries to send the message.

*Console.logs removed all except line 25*

closes #23

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -11,25 +11,42 @@ dotenv.config()
...
+const buildHeartbeat = async (backoff: number) => {
+  await new Promise(f => setTimeout(f, backoff * 1000));
+  // Build client node
+  let client = new ws(`${heartbeat_url}/heartbeat`);
+  //Bool is necessary to prevent sending after interval
+  let clientOn = true
   
-  setInterval(() => {
+  //catch WS errors. This is a required function so that the app does not crash
+  client.on('error', (error) => {
```
Comment (SpBills) [inline src/main.ts:22]: Cool. Didn't know this was required.

**Review by SpBills — APPROVED** [review]
LGTM
